### ISSUE TITLE
[Solved] How to use a pre-made axios instance with vue-mc Model?

### ISSUE THREAD

**Issue by isNaN** [FiguredLimited/vue-mc#101]
Hi.

I'm trying to use my own axios instance, with my preset headers with vue-mc. From our login we have quite a few headers set to be able to talk to our backend properly, as well as the logout being tied to that instance as well. I saw a reference elsewhere that I should extend vue-mc's Model class and overwrite the getRequest method. So I made a BaseModel class.

However the getRequest method wants to return a Request instance, which is a class not exported from vue-mc, and the axios instance seems to be in the send function of the Request class. So I dug into the code, and made my own identical BaseRequest to return from my BaseModel's getRequest class.

However the send function again wants to return a RequestError or a Response instance, neither of which are exposed. So I made a BaseRequestError and a ....

So this rabbit-hole just seems to go deeper, I end up getting new error messages from functions and classes expecting new classes or more methods from my instances every time, clearly this is not how it's intended to be used.

Are there any good examples on how I can just overwrite the getRequest-method of my extended Model class to achieve my intended results?

It would be great if there just was a simple param set once, (or twice then, for "BaseCollection" too). Something like this pseudocode:

```javascript
    import Vue from 'vue';
    import { Model, } from 'vue-mc';

    class BaseModel extends Model {

        constructor() {
            super();
            // set all models $http-client to our preset axios instance, which we've already set to Vue.prototype at login...
            this.$http = Vue.prototype.$http;
        }
    }

**Comment by isNaN** [comment]
Ok, so writing the above post triggered that ol' rubberduck in me, and I came up with this which seems elegant enough.

```javascript
    import _          from 'lodash';
    import Vue        from 'vue';
    import { Model, } from 'vue-mc';
    
    /**
     * BaseModel
     * A base model class using the application's default axios settings.
     * Note: Always extend from this class, not the vue-mc Model.
     * @version 0.0.3
     */
    class BaseModel extends Model {
        
        /**
         * Parses every request made by any Model in the system.
         * @param config  Config options for any restful http call.
         * @returns {Request} A new `Request` using the given configuration and our default axios instance's settings.
         */
        getRequest( config ) {
            // Vue.prototype.$http contains our axios instance, we extend the given config with it's settings.
            config = _.extend( config, Vue.prototype.$http.defaults );
            return super.getRequest( config );
        }
    }
    
    export default BaseModel;
```

So unless there's something I've failed to understand with the intent of vue-mc, this should be a working implementation?

**Comment by isNaN** [comment]
Added the same getRequest to a "BaseCollection" class, and everything seems to work fine.

Changed the title in case anyone else struggles with their settings the way I did.

**Comment by igorjacauna** [comment]
This can help if you want use the instance instead pass only configs to vue-mc instance: https://github.com/FiguredLimited/vue-mc/issues/23#issuecomment-538444274
