### ISSUE TITLE
Collection fetch with queries overwrite pagination

### ISSUE THREAD

**Issue by nomadinteractif** [FiguredLimited/vue-mc#112]
Good day!

Since I have upgraded to the latest version 0.5.0, I can't paginate using parameters.

In the previous version 0.4.0 this would work
collection.page(1).fetch({params : { query : 'blah'}})

But now, page get overwritten with params object.  This is related to the Base.js fetch function.  Probably this [commit ](https://github.com/FiguredLimited/vue-mc/commit/37d687411d7ef12497b6ef288792c9f1f33b06d4#diff-44bd02bec87d6b5f460fd772e9f40491)

```
fetch(options = {}) {        
        let config = () => defaults(options, {
            url     : this.getFetchURL(),
            method  : this.getFetchMethod(),
            params  : this.getFetchQuery(),
            headers : this.getFetchHeaders(),
        });
        return this.request(
            config,
            this.onFetch,
            this.onFetchSuccess,
            this.onFetchFailure
        );
    }
```

Instead of using lodash defaults, we can replace by defaultsDeep and it fix my problem.

Thank you

**Comment by rtheunissen** [comment]
This has been fixed and released as part of [v0.6.0](https://github.com/FiguredLimited/vue-mc/releases/tag/v0.6.0).
