### ISSUE TITLE
Vue version locked at 2.5.17

### ISSUE THREAD

**Issue by mikeebowen** [FiguredLimited/vue-mc#121]
https://github.com/FiguredLimited/vue-mc/blob/9d10603da70c9ae6650d4b0ee513d06b5df7b6fd/package.json#L41

The version of Vue that Vue-mc is using is locked at 2.5.17, which causes multiple versions of vue to be loaded in applications using the latest version of vue.

**Comment by rtheunissen** [comment]
What should this be, any 2.*?

**Comment by mikeebowen** [comment]
Yes, it should probably be: `"vue": "^2.5.17" `

**Comment by rtheunissen** [comment]
This has been fixed and released as part of [v0.6.0](https://github.com/FiguredLimited/vue-mc/releases/tag/v0.6.0).
