### ISSUE TITLE
getRequest never called in Model or Collection

### ISSUE THREAD

**Issue by throrin19** [FiguredLimited/vue-mc#126]
Hello,

I have a problem with the last version of vue-mc : 0.6.0
The method `getRequest` is never called in my models and collections and it works fine in 0.5.0.

I use that to set the request informations (baseURL and headers) for all collections/models requests : 

```js
import { request } from 'libs/session';

class MyCollections extends Collection {
    getRequest(config) {
        config.baseURL = request.defaults.baseURL;
        config.headers = request.defaults.headers;

        return super.getRequest(config);
    }
}
```

It's normal ? I see no informations about this breaking change in the changelog

**Comment by rtheunissen** [comment]
My apologies @throrin19, I wasn't following semver properly and renamed `getRequest` to `createRequest` between 0.5 and 0.6, which clearly breaks BC.

**Comment by rtheunissen** [comment]
I've added that in the changelog now. Will be more thorough in the future. 👍

**Comment by Kivt** [comment]
Update, please documentation. At http://vuemc.io/#model-request-custom it still `getRequest`

**Comment by rtheunissen** [comment]
Thank you @Kivt, updated.
