### ISSUE TITLE
Type mismatch in validation

### ISSUE THREAD

**Issue by BehindTheMath** [FiguredLimited/vue-mc#132]
https://github.com/FiguredLimited/vue-mc/blob/1904dd5c49f54d27b56dfb951a7437228e4c4e3d/src/Validation/index.js#L194-L203

If `test` is `true`, it's not a function, and can't be called.

**Comment by BehindTheMath** [comment]
Truthfully, I don't understand why `stubTrue()` is needed at all, and why it's better than `true`.

**Comment by JonLev** [comment]
Could anyone answer this issue ? It blocks typescript support for too long...

**Comment by JonLev** [comment]
@BehindTheMath the commit was done 15 month ago. I'm not even sure anyone know the reason anymore... can't we work around ?

**Comment by BehindTheMath** [comment]
Ok, I took another look at this, and I just realized that this was my mistake.

I thought the code said `stubTrue()`, which would return `true` immediately, and in which case my original questions would be valid. But it doesn't say that, it says `stubTrue` without calling it, and it's used as a default rule function that always returns true.

 I'm going to fix my TS branch.
