### ISSUE TITLE
Demo App

### ISSUE THREAD

**Issue by gabrielwillemann** [FiguredLimited/vue-mc#14]
Hello,

There is a demo app? Would be very interesting!

Congratulations for the project.

**Comment by rtheunissen** [comment]
Not yet but there will be one soon, hopefully in the next week.

**Comment by webmint** [comment]
Yeap demo needed cause from documentation cant get hot to implement it

**Comment by rtheunissen** [comment]
Demo is now available at [/demo](https://github.com/FiguredLimited/vue-mc/tree/master/demo) 🎉
