### ISSUE TITLE
Is there any ways to add attributes in Collections?

### ISSUE THREAD

**Issue by nikkanetiya** [FiguredLimited/vue-mc#15]
Hello,

This lib. is much useful particularly for me to built frontend in Vue & backend powered by Laravel. I was having to question/suggestions if it is not already included. 

1. Is there any way to add a custom attribute to collections? What I want to do is append some parameters to fetch url.
2. Is there any way to add custom HTTP methods to model other than CRUD?

**Comment by rtheunissen** [comment]
You can use [options](http://vuemc.io/#collection-options) for both, if by custom HTTP methods you mean override what's used for fetch, save and delete?

**Comment by nikkanetiya** [comment]
For example, I want to define the methods 'follow-user' which will make API call just like fetch/update does.

**Comment by rtheunissen** [comment]
You can use something like this:
```
followUser(user) {
    let config = {
        // url
        // method
        // data
        // params
        // headers
    };

    return this.getRequest(config).send().then(() => {
        // Handle success here
    }).catch((error) => {
        // Handle failure here
    });
}
```

**Comment by rtheunissen** [comment]
On top of that, you can use this to get the URL, where `follow` is the route key.

```
let route  = this.routes()['follow'];
let params = this.getRouteParameters();
let url    = this.getURL(route, params);
```

**Comment by nikkanetiya** [comment]
Thanks, 

I think it will work, but I was just asking if there is anything pre-built with a collection.

```
return this.getRequest(config).send().then(() => {
        // Handle success here
    }).catch((error) => {
        // Handle failure here
    });
```

Regarding my first question I was asking if we can set any attribute like what we have in the model. I have filters which values are dynamic & I need it to pass with fetch URL as a query string. There are many cases where we need this kind of thing rather than just plan 'fetch'. 

> i.e. /fetch/{id}?order=desc&orderBy=name

**Comment by rtheunissen** [comment]
That snippet will work within a model or collection. 😄 At the moment there isn't a nicer interface for non-crud HTTP, as everything starts with a `getRequest` which you can `send`.

> I was asking if we can set any attribute like what we have in the model

Yes, you can use options for that. For example:

```js
class ExampleCollection extends Collection {
    ...
    getRouteParameters() {
        return _.merge(super.getRouteParameters(), {
            order: this.option('order', 'asc'),
            orderBy: this.option('orderBy', 'name'),
        });
    }
}

// Initialise
let collection = new ExampleCollection(models, {order: 'desc', orderBy: 'name'});

// Set option later if you like
collection.setOption('order', 'asc');
```

Would something like that solve your problem?

There really should be a nicer way to support this.. maybe `setRouteParameter`?

**Comment by rtheunissen** [comment]
Released as v0.2.0, see http://vuemc.io/#collection-attributes

**Comment by nikkanetiya** [comment]
Yes, seems perfect. Thanks

**Comment by nikkanetiya** [comment]
Is it there in v0.2.0? If I am not wrong, the newly added thing is not there with v0.2.0 I just tried twice with npm. Correct me I am wrong because I am seeing any get methods in vue-mc.js file.

**Comment by rtheunissen** [comment]
@nikkanetiya I think it was v0.2.1 sorry
