### ISSUE TITLE
Website http://vuemc.io/ is down

### ISSUE THREAD

**Issue by Rikcon** [FiguredLimited/vue-mc#158]
Hello, first of all thank you for your time developing this lovely package, i use it in a project and absolutely love it ! 

Your website is down ( http://vuemc.io/ ) seems you forgot to prolongue your domain name ?

**Comment by rtheunissen** [comment]
Thank you @Rikcon I just renewed the domain - thought for sure that auto-renew was enabled. 😬 

It should be up again soon.
