### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Flygenring** [FiguredLimited/vue-mc#19]
It would be quite helpful with an overview of changes between versions that is more detailed than the [release](https://github.com/FiguredLimited/vue-mc/releases) and less than the [commit](https://github.com/FiguredLimited/vue-mc/commits) overview.

Whether it's kept in the readme, the documentation, the release overview, or somewhere else is a matter of taste, but I think it should be kept and might as weel be kept public ;)

**Comment by rtheunissen** [comment]
Great idea, I'll retroactively update the releases, create and maintain a changelog file. :+1:

**Comment by rtheunissen** [comment]
Changelog now available as [CHANGELOG.md](https://github.com/FiguredLimited/vue-mc/blob/master/CHANGELOG.md). Also amended the release notes.
