### ISSUE TITLE
Axios configurations (client)

### ISSUE THREAD

**Issue by rmartins90** [FiguredLimited/vue-mc#23]
I need to set defaults for axios like "withCredentials" property, baseUrl, headers, etc (and also interceptos). I tried to set it to axios.defaults on app.js but it didn't work. How can I achieve this?

**Comment by rmartins90** [comment]
I found out that defaults does work, except for baseUrl. Either way it would be great to be able to specify your own axios instance.

**Comment by rtheunissen** [comment]
I wonder why `baseUrl` doesn't work. 🤔 

The policy from the start was to not be tightly coupled with axios. You can extend `Request` to adjust the config in the constructor and return your extended instance in the model or collection's `getRequest(config)` method.

**Comment by rmartins90** [comment]
Yes but that way I'll need to create a base class for all my Models and Collections or override getRequest in all of them.

**Comment by rtheunissen** [comment]
It's good practice to extend them anyway.

```
import { Model as Base } from 'vue-mc'

class Model extends Base {
    ...
}
```

Then extend your own base instead.

**Comment by rtheunissen** [comment]
We should add some documentation around specifying your own client.

**Comment by Sarke** [comment]
You can do something like this (ES6):

```javascript
import { Collection } from 'vue-mc';

export default class extends Collection {
    getRequest(config) {
        config.baseURL = 'http://localhost:8080/';
        config.auth = {
            username: 'johndoe',
            password: 'password1',
        };

        return super.getRequest(config);
    }
}
```

**Comment by throrin19** [comment]
It's not possible to set specific axios instance ?

**Comment by rtheunissen** [comment]
At the moment you can't set it, but you can produce it by overriding `getRequest()`.

**Comment by rtheunissen** [comment]
The design here is to allow for any HTTP client to be used, not just axios.

**Comment by rtheunissen** [comment]
I'm going to close this because there isn't work in progress here. We don't want to be coupled tightly with axios so the only way is to override `getRequest` on your base model/collection.

**Comment by rockfreak** [comment]
Did you ever get around to writing some documentation on to how to specify your own client?

**Comment by CristianaPereira** [comment]
When you call fetch method, send your configs like:

  this.myCollection.fetch({'withCredentials': true}).then((response) => {
      console.log(response);
        // Handle success here
    }).catch((error) => {
        // Handle failure here
    })

**Comment by igorjacauna** [comment]
For my nuxt application I solve this creating 3 classes based on classes used by vue-mc:
```javascript
import { extend, get } from 'lodash'
import Vue from 'vue'

export class MyResponse {
  constructor(response) {
    this.response = response
  }

  getData() {
    return get(this.response, 'data', null)
  }

  getStatus() {
    return get(this.response, 'status')
  }

  getHeaders() {
    return get(this.response, 'headers', {})
  }

  getValidationErrors() {
    return get(this.response, 'data', null)
  }
}

export class MyRequestError {
  constructor(error, response) {
    this.error = error
    this.response = response
    this.stack = new Error().stack
    this.message = error.message
  }

  toString() {
    return this.message
  }

  getError() {
    return this.error
  }

  getResponse() {
    return this.response
  }
}

export class MyRequest {
  constructor(config) {
    this.config = config
  }

  send() {
    this.config = extend(this.config, Vue.prototype.$nuxt.$axios.defaults)
    return Vue.prototype.$nuxt.$axios.request(this.config).then((response) => {
      return new MyResponse(response)
    }).catch((error) => {
      throw new MyRequestError(error, new Response(error.response))
    })
  }
}
```

In BaseModels and BaseCollection, override the `getRequest()` with:

```javascript
export class BaseModel extends Model {
  getRequest(config) {
    return new MyRequest(config)
  }
}

export class BaseCollection extends Collection {
  getRequest(config) {
    return new MyRequest(config)
  }
}
```
The key is in `send()` method in `MyRequest` class where I use `nuxt` `$axios` instance:

```javascript
send() {
    this.config = extend(this.config, Vue.prototype.$nuxt.$axios.defaults)
    return Vue.prototype.$nuxt.$axios.request(this.config).then((response) => {
      return new MyResponse(response)
    }).catch((error) => {
      throw new MyRequestError(error, new Response(error.response))
    })
}
```

**Comment by lucafaggianelli** [comment]
For those who got completely crazy about why `getRequest` doesn't work, it has been renamed to `createRequest` in v0.6.0:

https://github.com/FiguredLimited/vue-mc/blob/master/CHANGELOG.md#060---2019-08-15

**Comment by Nerphist** [comment]
How I overrided createRequest to use my axios client with interceptors for tokens:
`createRequest(config) {
        config.headers = Vue.prototype.$http.defaults.headers.common;
        return {
            send: () => axios(config).then(response => {
                return {
                    getData: () => response.data,
                    getStatus: () => response.status,
                }
            })
        };
    }`
