### ISSUE TITLE
Improve documentation for custom methods

### ISSUE THREAD

**Issue by rmartins90** [FiguredLimited/vue-mc#26]
http://vuemc.io/#model-request-custom

It's still not clear how to write a custom method, I'm still trying to figure out which method do I need to call to save API's response to model.

**Comment by rtheunissen** [comment]
Let's try an example. You have a `User` that can **subscribe** to a `Channel`.

```js
class User extends Model {
    defaults() {
        return {
            id: null,
        }
    }
}

class Channel extends Model {

    defaults() {
        return {
            id: null,
        }
    }

    routes() {
        return {
            save:       '/channel/{id}'
            subscribe:  '/channel/{id}/subscribe'
        }
    }

    subscribe(user) {
        let method = 'POST';
        let route  = this.getRoute('subscribe');
        let url    = this.getURL(route);
        let data   = {user: user.id},
        
        return this.getRequest({method, url, data}).send();
    }
}

let channel = new Channel({id: 1});

let user = new User({id: 2});

channel.subscribe(user).then(() => {
    // Successfully subscribed
}).catch((error) => {
    // Something went wrong
});
```

Your controller would then receive the following request:

```
POST /channel/1/subscribe "{user: 2}"
```

**Comment by rtheunissen** [comment]
I agree that the documentation needs some work here. 👍

**Comment by sifex** [comment]
There's also a missing `this.saving = true` and `this.saving = false` required if you use that

**Comment by MaeseppTarvo** [comment]
Can anyone make demo for this? Using the channel.subscribe() gives unresolved route channel.subscribe.

**Comment by robjbrain** [comment]
As per the original comment (and my other issue raised) this could still do with alot better documentation.

An exact copy and paste of @rtheunissen 's code results in an error:

```
http://domain.test/channel/undefined/subscribe 
```

And since there's so little documentation it's impossible to debug what's going on. Presumably it has something to do with using `getRouteParameters()` but again there's no documentation on that, just a mild reference to it...

It also doesn't seem to account for what's set in options such as `options: {methods: subscribe: "PATCH"}`. Or maybe it does, but there's no way of knowing.

It's a shame because this feels like a great package but there's so many black holes to get sucked into because the documentation is so vague. It all just becomes trial and error, which isn't what you want from a package.

**Comment by eduardobc** [comment]
Note: You can use getURL(route, parameters = {}) to resolve a route’s URL directly.
`let url    = this.getURL(route, this.getRouteParameters())`

passing getRouteParameters() the url parameter will be solved :)

**Comment by rtheunissen** [comment]
@robjbrain you're right that the example I suggested has a mistake in it - we're not passing the route parameters to the URL builder. Custom requests were not a priority for us so naturally came as a "oh yeah you could probably do that if you want". I'm going to update the example, and base the documentation on that.

```
class User extends Model {
    defaults() {
        return {
            id: null,
        }
    }
}

class Channel extends Model {

    defaults() {
        return {
            id: null,
        }
    }

    routes() {
        return {
            save:       '/channel/{id}'
            subscribe:  '/channel/{id}/subscribe'
        }
    }

    subscribe(user) {
        let method = this.getOption('methods.subscribe');
        let route  = this.getRoute('subscribe');
        let params = this.getRouteParameters();
        let url    = this.getURL(route, params);
        let data   = {user: user.id},
        
        return this.getRequest({method, url, data}).send();
    }
}

let channel = new Channel({id: 1});

let user = new User({id: 2});

channel.subscribe(user).then(() => {
    // Successfully subscribed
}).catch((error) => {
    // Something went wrong
});
```

**Comment by rtheunissen** [comment]
Almost a year later... https://vuemc.io/#model-request-custom
