### ISSUE TITLE
Custom attribute will not append in pagination fetch request

### ISSUE THREAD

**Issue by nikkanetiya** [FiguredLimited/vue-mc#27]
Hello,

Thanks, time & supports to create & maintain vue-mc. The custom attribute of a collection will not append to fetch request, please correct if I am wrong. Because of this.

https://github.com/FiguredLimited/vue-mc/blob/master/src/Structures/Collection.js#L626

**Comment by rtheunissen** [comment]
You're right, but it's not supposed to. Collection attributes are included in route parameters by default, but not query parameters. For example, if you had an attribute on a collection called "group" with value "1", and a URL like "/example/{group}", it will be replaced in the URL to produce "/example/1", but won't also append it as a query string. 

To do this, you will need to override the `getFetchQuery` method.

**Comment by nikkanetiya** [comment]
@rtheunissen Yes already did in my local version, just suggesting if you think this might be useful to other developers if you add a method to add query parameters. Nevermind it is also very easy to override it as per need.

**Comment by rtheunissen** [comment]
The design encourages overriding instead of setting, which moves configuration and logic into the model and out of the components.

**Comment by nikkanetiya** [comment]
@rtheunissen Totally agree.
