### ISSUE TITLE
Sorting on the server

### ISSUE THREAD

**Issue by bisworld** [FiguredLimited/vue-mc#28]
It would be nice to add functionality to implement sorting on the server, something like that:

`model.page(1).sorting({ name: 'desc' }).fetch() => ?page=1&sort=name&order=desc`

or set all query params

`model.queryParams({ page: 1, sort: 'name', order: 'desc' }).fetch() => ?page=1&sort=name&order=desc`

it would be convenient to use with route

`{ params: this.$route.query }`

**Comment by rtheunissen** [comment]
If you wanted to fetch a paginated collection with some sorting parameters, you could do it like this:

```
collection.set('sort', 'name');
collection.set('order', 'desc');

...

getFetchQuery() {
    return {
        page:  this.getPage(),
        sort:  this.get('sort'),
        order: this.get('order'),
    }
}
```

**Comment by bisworld** [comment]
Thank you!
This is what I need.

Can help with another question.
The documentation says:

> Validation errors are automatically set on a model and can be accessed as model.errors. They are set when a save request receives a 422 Unprocessable Entity response. You can adjust how this is determined by overriding isValidationError(response)

But in the code there is no such function.
I have the answer backend here is the format, how to properly process it:

`{"message":"The given data was invalid.","errors":{"name":["The name must be at least 6 characters."]}}`

**Comment by rtheunissen** [comment]
Sorry for missing this one @bisworld. Did you manage to get it working?

**Comment by bisworld** [comment]
No, I did not do it, I'm waiting for the release of the missing functionality.

**Comment by rtheunissen** [comment]
> But in the code there is no such function.

The method was changed to `isBackendValidationError` after front-end validation was implemented.

**Comment by rtheunissen** [comment]
This in on Model:

```js
    /**
     * Called when a save request resulted in a validation error.
     *
     * @param {Object} errors
     */
    onSaveValidationFailure(error) {
        let errors = error.getResponse().getValidationErrors();

        if ( ! _.isPlainObject(errors)) {
            throw new ResponseError(
                'Validation errors must be an object', error.getResponse());
        }

        this.setErrors(errors);

        Vue.set(this, 'fatal',  false);
        Vue.set(this, 'saving', false);
    }
```

What you could do is override `setErrors`, or we could implement a method like `getValidationErrors(error)` that might be a more appropriate override?
