### ISSUE TITLE
ResponseError

### ISSUE THREAD

**Issue by raulrodfe** [FiguredLimited/vue-mc#35]
"Expected an array of models in fetch response"
--------------------------------------------------------
this is my json response:
code: 200
data:[{id: 1, cif: "B12312312", razon_social: "Formacion Futuro S.L", email: "formacion@formacion.com",…}]
message: null
status:true

---------------------------------------------------------
I can´t get my response. What is the proble?

**Comment by rtheunissen** [comment]
What this means is that the schema of the response does not match the assumption that the response will just be a single array of models. There is an update in the works to make this easier to configure, but for the time being what you'll need to do is what's explained here: https://github.com/FiguredLimited/vue-mc/issues/30

**Comment by los420** [comment]
Hey, any news about this 'work in progress' update? i have the exact same issue
Thanks

**Comment by rtheunissen** [comment]
@los420 we've been developing vue-mc internally but haven't made a formal release recently. It's a common issue because response schemas can't be expected to be consistent between projects. Override `update` for now, I'm sorry we don't have a proper solution for this released yet.
