### ISSUE TITLE
toArray and toObject

### ISSUE THREAD

**Issue by throrin19** [FiguredLimited/vue-mc#40]
I'm surprised to see this library has no methods `toArray` and `toObject` on Collections and models to use this on non-compatibles vueJS components.

It's possible to add this vital functions ?

Thanks

**Comment by rtheunissen** [comment]
Would `toObject` just be `attributes`? Not sure what `toArray` would return.

**Comment by throrin19** [comment]
- `toObject` : return attributes model
- `toArray` : On collection only, return an array of toObject models

**Comment by rtheunissen** [comment]
Yeah can add these, can't see why not. Good call. 👍

**Comment by throrin19** [comment]
Oh, for the `toObject() I just seen the `toJSON()`
