### ISSUE TITLE
Representing model relationships

### ISSUE THREAD

**Issue by burningbman** [FiguredLimited/vue-mc#46]
Are you planning to add support for attributes that are models?
I'm not sure if the use case is general enough, but I was looking for the following: 
- A model is returned when calling get for that attribute on the model
- The attribute is only marked as changed when a different models is set for the attribute (the related model's attributes can change without marking this attribute as changed)
- The id of that model is passed for that attribute when saving

This might be along the lines of the feature you mention in Issue #39.

**Comment by Acen** [comment]
>Are you planning to add support for attributes that are models?

Once we work out those kinks in #39 I think so.
There are a couple of extra questions that might need answering in terms of things like, do we want to allow a nested model to be locked to one type - like how a collection has a defined model which it has a collection of - or would we want to look at a polymorphic possible solution?

There are a few options which are already supporting model nesting. E.g. [`validateRecursively`](http://vuemc.io/#model-options) which if you look through the [`validateAttribute`](https://github.com/FiguredLimited/vue-mc/blob/d5530be9b7f24f1a7bf8b6515117d497bf6e0a62/src/Structures/Model.js#L604) checks each attribute within the model and, if it has a `validate` method will validate itself.


The way I've been nesting models is by using `Vue.set()` then a standard getter to allow the nested model to be fully reactive, but I'm honestly unsure if it's even the safest way to push data onto the model.

```javascript
    set method( billing_method ) {
        Vue.set(this, 'billing_method', billing_method);
    }

    get method() {
        return this.billing_method || null;
    }
```

**Comment by Acen** [comment]
I'm closing this after adding some comments on #39 with what you've said. Comment there if you have anything else to add about this. Super valuable though, thanks @burningbman.
