### ISSUE TITLE
Documentation suggests installing hidden globals

### ISSUE THREAD

**Issue by kvdveer** [FiguredLimited/vue-mc#5]
From documentation: 

```
// Set the on the global on the window so that you don't have to import
// the base classes in every model and collection class or component.
window.Model = Model;
window.Collection = Collection;
```

This is really bad practice. It leads to maintainable code, and all kinds of conflicts. No-one should ever do that, and documentation should certainly not recommend it.

Importing these symbols is a single line, which has two purposes: 

1. explain to babel where to find the symbol, 
1. explain to the reader of the code what library is being used here. 

Purpose no1 can be circumvented by using a global import, but purpose no2 is still really relevant, and should not be left out.

**Comment by rtheunissen** [comment]
Quoting from #6 

> The reason we went for globals here was to make it as easy as possible for us to migrate to this version of the library (rather than our own internal one). It's a flaw in our setup because we have a structure like this:

> lib.js (package dependencies, should not change often)
app.js (application bootstrapping)
module1.js (page-specific module)
module2.js

> If we imported Model or Collection in both bundles module1.js and module2.js, we'll end up with two instances of the same dependency, because the two modules are not aware of each other.

> Even if we created globals for ourselves in app.js, we'll be embedding lodash and moment in our app.js, which should ideally only be in lib.js.

> I agree with you though - we should never rely on a global peer dependency, everything should be imported where required and **it's up to the client to bundle them efficiently**.

**Comment by rtheunissen** [comment]
IDE support is also a hassle when you're assuming globals.

**Comment by rtheunissen** [comment]
This is now a work in progress on the 0.2 branch.
