### ISSUE TITLE
Library not compatible with babel 7.0.0beta.48+

### ISSUE THREAD

**Issue by throrin19** [FiguredLimited/vue-mc#54]
Hello, I have a problem with vue-mc and Babel.

If I update babel in last versions (7.0.0 beta 48 and more) I have this error on my project if I ass custom method on your Collection class :

**Input Code**

```js
class MyClass extends Collection {
    setPageSize(pageSize) {
        this._pageSize = pageSize;
    }
}

const obj = new MyClass();

obj.setPageSize(12); // TypeError: obj.setPageSize is not a function
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "plugins": [
        "lodash"
    ],
    "presets": [
        "poi",
        ["@babel/env", {
            "targets": {
              "browsers": [
                ">0.25%",
                "not ie 10",
                "not op_mini all"
              ]
            }
        }]
    ]
}
```

**Environment**
- vue-mc version : 0.2.4
- Babel version(s): 7.0.0-beta.48, 7.0.0-beta.49
- Node/npm version: Node v8.11.1 / NPM v5.8.0
- OS: OSX 10.13.4
- Monorepo: yes
- How you are using Babel: `loader`

I've create same issue on Babel repo : https://github.com/babel/babel/issues/8063

**Comment by throrin19** [comment]
@rtheunissen any news about that ? It's a really blocking bug

**Comment by rtheunissen** [comment]
@throrin19 I noticed that you closed the PR #56, why was that?

**Comment by rtheunissen** [comment]
Is this potentially a bug with Babel and not vue-mc?

**Comment by throrin19** [comment]
It was a test with last version of babel but it does not works correctly.

**Comment by throrin19** [comment]
Yes, after test it was a bug with babel but I have no response

**Comment by throrin19** [comment]
No I have no responds from Babel

**Comment by throrin19** [comment]
Ok, I found the bug. After research I try to update the preset I use : babel-preset-poi but the package use old versions (7.0.0.beta.40).

I try to reproduce configuration with last versions packages and it works fine :)
