### ISSUE TITLE
How to handle uploads?

### ISSUE THREAD

**Issue by stephandesouza** [FiguredLimited/vue-mc#55]
Is there any simple way to upload a `File` Object via vue-mc?

**Comment by stephandesouza** [comment]
Doing some progress i achieve by creating a new method and overwriting all data to `FormData`

https://gist.github.com/stephandesouza/b7722252419f44b72bad86f6225945e6

**Comment by rtheunissen** [comment]
I think we could probably create an `upload` method alongside fetch, save, and delete?

**Comment by rtheunissen** [comment]
There's an upload method on master now, but not released yet. I'll come back to this issue to let you know when there is a stable release but will close for now.

**Comment by sifex** [comment]
Yea @rtheunissen getting a protocol error now, might override it by using a lot of the saveData saveHeaders, did you want a PR to fix this?
