### ISSUE TITLE
Use date-fns for date validations

### ISSUE THREAD

**Issue by Dylan-Chapman** [FiguredLimited/vue-mc#57]
Moment.js is a fairly large dependency, especially if this is the only package you have that's using it. It'd be nice if date-fns was used instead, or simply supplying a way to use non-date related validation rules without Moment being imported, then we can redefine our own date-related rules using whatever date library.

**Comment by rtheunissen** [comment]
I think the intention was that tree-shaking would prevent the entire library to be imported (if at all). I'll check out date-fns because moment is overkill for sure.

**Comment by rtheunissen** [comment]
✨
