### ISSUE TITLE
Allow for async validation rules

### ISSUE THREAD

**Issue by Dylan-Chapman** [FiguredLimited/vue-mc#58]
As far as I can tell, it's currently impossible to have async validation rules.

Common scenario: You need to check if an email address is available or already taken when a user is changing their email address.

I'm migrating some validation from VeeValidate to models, and how they handle it is letting rules return a promise that resolves ```{  valid: Boolean }```. [Docs Reference](https://baianat.github.io/vee-validate/examples/async-backend-validation.html) and [Code Reference](https://github.com/baianat/vee-validate/blob/master/src/core/validator.js#L256)

**Comment by rtheunissen** [comment]
This is an awesome idea, thanks for suggesting it. Looks like we should adjust `validateAttribute` in `Model` to use and honour a returned Promise. The callback for the rule should then return a promise.

**Comment by rtheunissen** [comment]
This has now been implemented in master but because it's a breaking change, it would need to wait for 2.0

**Comment by Dylan-Chapman** [comment]
@rtheunissen I could be doing something wrong, but there seem to be some issues.

For example, if I have the following rule defined:

```javascript
const emailAvailable = rule( {
  name: "emailAvailable",
  test: value => new Promise( ( resolve, reject ) =>
    Vue.axios.get( "users/available", { params: { email: value.trim() } } )
    .then( response => {
      if ( response.data ) {
        resolve();
      } else {
        resolve( "This email is already being used" );
      }
    } )
    .catch( error => {
      reject( error );
    } ) )
} );
```

And then in a model I have:

```javascript
validation() {
  return {
    email: required.and( email ).and( emailAvailable )
  };
}
```

This will return true (instead of a promise) once the ```email``` has passed, regardless of the contents of ```emailAvailable``` (as long as it's returning a promise).

If I try to inline the rule, I have the same problem: 

```javascript
validation() {
  return {
    email: required.and( email ).and( value => new Promise( ( resolve, reject ) =>
      Vue.axios.get( "users/available", { params: { email: value.trim() } } )
      .then( response => {
        if ( response.data ) {
          resolve();
        } else {
          resolve( "This email is already being used" );
        }
      } )
      .catch( error => {
        reject( error );
      } ) ) ),
  };
}
```

HOWEVER, if I inline the validation rule, but it's NOT part of a chain, this validates **correctly:**

```javascript
validation() {
 return {
  email: value => new Promise( ( resolve, reject ) =>
   Vue.axios.get( "users/available", { params: { email: value.trim() } } )
   .then( response => {
    if ( response.data ) {
     resolve();
    } else {
     resolve( "This email is already being used" );
    }
   } )
   .catch( error => {
    reject( error );
   } ) )
 };
}
```

Which would lead me to think the problem is just with chaining, but the following also fails in the same way:

```javascript
validation() {
 return {
  email: emailAvailable
 };
}
```

So it seems like the problem is with the actual ```rule```?

**Comment by rtheunissen** [comment]
You were absolutely right on this, we needed to rewrite the rule evaluation to always use promises. All rules are now evaluated asynchronously and you should see the expected behaviour on `master`.

Also, for what it's worth, I think you may be able to simplify your rule a bit:
```js
validation() {
  return {
    email: required.and(email).and((value) => {
      return Vue.axios.get("users/available", {params: {email: value.trim()}})
        .then((response) => {
          if ( ! response.data) {
            return "This email is already being used";
          }
        }),
  });
}
```
