### ISSUE TITLE
Strange behavior of property type Array

### ISSUE THREAD

**Issue by maxvanceffer** [FiguredLimited/vue-mc#60]
When define my model like this 

```
  defaults () {
    return {
      'keys': []
    }
  }

  mutations () {
    return {
      'keys': Array
    }
  }
```

and response contains 
```
{keys: [1,2,3]}
```
model contains next data 

```
_attributes.keys === [[1,2,3]]
```

**Comment by rtheunissen** [comment]
This is actually not a bug, but the nature of `Array`. For example:

```js
let a = [1,2,3];

Array(a);         //   [ [1,2,3] ]
Array(Array(a))   // [ [ [1,2,3] ] ]
```

I think what you're looking for is [`Array.from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)
