### ISSUE TITLE
Why does the default path for update use POST instead of PUT?

### ISSUE THREAD

**Issue by Sarke** [FiguredLimited/vue-mc#61]
REST standard calls for PUT when updating, why is POST the default?

**Comment by rtheunissen** [comment]
Many projects use GET and POST exclusively as "read" and "write", where specific methods like PUT and PATCH might not be handled correctly. Another good case for POST as the default is for projects that have the same controller/endpoint for create and update. For example, a "save" method might create if the ID is `null`, or update if the ID is set. 

We opted for the "most supported" option, while providing an easy way to adjust this in the options or overriding the getter. You can adjust it with the "methods.update" option, see http://vuemc.io/#default-request-methods. If you have a base model (recommended), this should be an easy adjustment.
