### ISSUE TITLE
More basic documentation and examples for fetching from an API

### ISSUE THREAD

**Issue by robjbrain** [FiguredLimited/vue-mc#66]
Would it be possible to get some more basic examples in the documentation. There isn't any examples of fetching from an api, only creating from a hard coded array.

Perhaps it's too simple a question but i've been really struggling. Right now this is the only thing I can get working to get an instance of a model from an API, but i'm sure it can't possibly be right as it seems far too convoluted.

```
// Task.vue
// The template would be displaying details about a single Task
export default {
        props: {
            taskId: {
                type: Number,
                default: 1
            },
        },
        created () {
            new Task({id: this.taskId}).fetch().then(response => {
                this.task = new Task(response.response.data);
            }).catch((error) => {
                console.log(error);
            });
        },
        data: function() {
            return {
                task: null
            };
        },
    };

// Json Response:
{"id":1,"title":"Task 1","description":"A description"},
```

All i'm trying to do is get a single instance of a Task, in Laravel it would look something like this:

```
$task = Task::find(1);

$task->doSomething();
echo $task->title;
// etc
```

How would you get a single instance of a Task with the id of 1 using vue-mc?

The documentation shows:

```
// Create a new task with initial attributes.
let task = new Task({title: 'Task 1'});

console.log(task.doSomething());
console.log(task.title);
```

But obviously that's not using fetch or getting data from a database?

Sorry for what is probably a very stupid and simple question but it's really not at all clear and hours of googling has got me nowhere. I've read every single issue hoping someone would at least have posted an example when having another issue, but there's nothing. It would be great if the docs had more examples of things like this even if it seems obvious to some people.

**Comment by rtheunissen** [comment]
It's a perfectly valid question. Fetching a model hasn't come up very much because it's usually collections that are fetched, and models that are saved. For this example, you could simplify it a bit:

```js
export default {
    props: {
        taskId: {
            type: Number,
            default: 1
        },
    },
data: function() {
        return {
            task: new Task({taskId: this.taskId}),
        };
    },
    mounted() {
        this.task.fetch().then(() => {
             // Fetched!
        });
    },
};
```

**Comment by robjbrain** [comment]
Thanks alot that does make it alot simpler. It would be great if there was some sort of `find()` function as well.

Presumably this.form is available and updated within then()?

**Comment by rtheunissen** [comment]
I'm not sure what exactly `this.form` is but you can use `this` as the vue instance because of the short arrow function syntax doing a bind.

**Comment by rtheunissen** [comment]
Closing this because there doesn't seem to be further action required. Let me know if this is not the case.
