### ISSUE TITLE
[Minor] HTTPS on vuemc.io

### ISSUE THREAD

**Issue by sifex** [FiguredLimited/vue-mc#68]
Just noticed this on https://vuemc.io

![screen shot 2018-08-18 at 11 49 50 pm](https://user-images.githubusercontent.com/2058557/44299906-80912e00-a341-11e8-889b-eba35c3e506e.png)

Also there's no redirect from http to https

**Comment by rtheunissen** [comment]
I'll check out the Github pages settings for those.
