### ISSUE TITLE
[Issue] Mutating to Collection causes Errors

### ISSUE THREAD

**Issue by sifex** [FiguredLimited/vue-mc#69]
Related to https://github.com/FiguredLimited/vue-mc/issues/9#issuecomment-375142071.

## Issue
I've run into some errors where my User model has a MembershipList collection similar to below

```json
{
	"name": "Test",
	"email": "test@test.com",
	"memberships": [
		{
			"id": 1
		}
	]
}
```

When I try to cast `"memberships"` to MembershipList, it seems to throw a tonne of Errors. Haven't looked too much into it, but from the outside it looked like a recursion error.

```js
// Attribute mutations.
mutations () {
	return {
		memberships: (memberships) => {
			return new MembershipList(memberships)
		}
	}
}
```

so using the following seemed to solve it.

```js
// Attribute mutations.
mutations () {
	return {
		memberships: (memberships) => {
			if (typeof memberships.models === 'undefined') {
				return new MembershipList(memberships)
			}
			return memberships
		}
	}
}
```

## Possible (better) Solution

Seems like an easy fix to this is to just test to see if the collection is accepting an array or if it's accepting another one of itself.

Just a quick request to see if @rtheunissen is happy with me fixing this like that & I'll submit a PR.

**Comment by rtheunissen** [comment]
@sifex so the suggested solution is to check if the `models` param is a Collection, and if so, use its `models`? I'd be curious to see why the first case breaks - there might be a way to fix that without changing the Collection constructor. 

I'll write a failing test into master so we can take a look at fixing it.

**Comment by sifex** [comment]
Not necessarily the models param, but if I pass `new User(new User({ id: 1 }))`, I kinda don't want it to throw an error. 

I should have prefixed by saying the reason this is becoming an issue for me is that VueX can only store a basic JSON object, and does not accept a User object. (I'll confirm this after work today as I'm more using this on a hobby startup)
