### ISSUE TITLE
use sort() in template

### ISSUE THREAD

**Issue by haayman** [FiguredLimited/vue-mc#71]
Hi,

I've got this list of items that I want to be displayed in a certain sort order. I thought I'd use it in a template like:
`<item v-for="item in itemList.models.sort('field')"></item>`
but since sort() doesn't return anything this doesn't work

I've 'solved' this by sorting anytime an item is added or when an item has changed. This way it's not possible to display the list twice in different sort orders. 

Any suggestions?

**Comment by rtheunissen** [comment]
I think the best way to do this is to use a computed property or method with a sort type to produce a sorted version of the collection. For example,

```js
/**
 * @returns {Array}
 */
itemsSortedBy(property) {
    return _.sortBy(this.itemList.models, property);
}

/**
 * @returns {Array}
 */
itemsSortedByName() {
    return this.itemsSortedBy('name');
}
```

```html
<item v-for="item in itemsSortedByName"></item>
````
