### ISSUE TITLE
Save ignores options like headers

### ISSUE THREAD

**Issue by tmeisel** [FiguredLimited/vue-mc#73]
With PR #44 , custom options were added to fetch requests. I'm using this to apply the access token to the request with something like `fetch({headers: {Authorization: 'Bearer ...'}})`.

Now this doesn't work with `save()`, the options are not applied. I'm wondering why is that and if it would be a reasonable change. To test the functionality, I patched my `vue-mv.es.js`. Obviously, not a permanent solution at all. 

The status quo looks like this:
```
var config = function config() {
    return {
        url: _this5.getSaveURL(),
        method: _this5.getSaveMethod(),
        data: _this5.getSaveData(),
        params: _this5.getSaveQuery(),
        headers: _this5.getSaveHeaders()
    };
};
```

which is changed to:

```
{
        key: 'save',
        value: function save() {
            var _this5 = this;

            var options = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};

            var config = function config() {
                return defaults(options, {
                    url: _this5.getSaveURL(),
                    method: _this5.getSaveMethod(),
                    data: _this5.getSaveData(),
                    params: _this5.getSaveQuery(),
                    headers: _this5.getSaveHeaders()
                });
            };

            return this.request(config, this.onSave, this.onSaveSuccess, this.onSaveFailure);
        }
```

By now, it should be very clear that I'm not a frontend developer : ) But I wanted to point out this potential problem/inconsistency. Otherwise, I would appreciate an advise on how to deal with protected routes using vue-mc in general.

**Comment by rtheunissen** [comment]
I believe this has now been fixed and released as 0.4.0
