### ISSUE TITLE
Collection.save() doesn't send IDs for modified models when Model.shouldPatch() is true

### ISSUE THREAD

**Issue by BehindTheMath** [FiguredLimited/vue-mc#74]
Per the docs on `Collection.save()`:

>Instead of calling save on each model individually, a collection will encode its models as an array, using the results of each model’s `getSaveBody()` method, which defaults to the model’s attributes. You can override `getSaveBody()` on the collection to change this behaviour.

The issue with this is that if `Model.shouldPatch()` is `true`, only the modified fields will be sent, and the server has no way of knowing which model to update, since the ID field was never sent.

One possible way to remedy this would be to change `Collection.getSaveData()` to add the IDs for modified models when `Model.shouldPatch()` is `true`:
```
getSaveData() {
    return this.getSavingModels().reduce((saveData, model) => {
        if (model.isNew() || !model.shouldPatch()) {
            saveData.push(model.getSaveData());
        } else {
            // For each modified model, get the save data, and add the ID
            saveData.push(Object.assign(Object.assign({}, model.getSaveData()), {id: model.id}));
        }

        return saveData;
    }, []);
}
```

Another possible way would be to make separate requests for new and modified models.

**Comment by rtheunissen** [comment]
This is a good catch, I did not consider this when saving a collection. I think that the model should always provide its ID, even if patching.
