### ISSUE TITLE
Fetch another domain

### ISSUE THREAD

**Issue by CristianaPereira** [FiguredLimited/vue-mc#77]
How can i define de url domain for my requests like fetch or save?
My api is running in another domain , is is possible without using "getRequest()", like overwrite baseURL or some other option ?

**Comment by inventionlabsSydney** [comment]
@CristianaPereira did you solve this? if so could you please help provide an answer?

**Comment by chrisformula** [comment]
Has any one got an answer for this?

**Comment by inventionlabsSydney** [comment]
Hey @chrisformula 
I ended up doing the following:

``` javascript
import {Model} from 'vue-mc'

export default class BaseModel extends Model {

	/**
	 * Override the base model to include the appropriate headers and the location of the server
	 **/
	getRequest( config ) {
    const isProd = process.env.NODE_ENV === "production";
    config.baseURL = isProd ? "https://<redacted>" : "http://localhost:8443"
    // Include the current JWT token
    config.headers = {'Authorization': "Bearer " + localStorage.getItem('token') || ''}
    return super.getRequest( config );
  }
}
```


Same thing with collection:

```javascript
import {Collection} from 'vue-mc'

export default class BaseCollection extends Collection {

	/**
	 * Override the base model to include the appropriate headers and the location of the server
	 **/
	getRequest( config ) {
      const isProd = process.env.NODE_ENV === "production";
    	config.baseURL = isProd ? "https://<redacted>" : "http://localhost:8443"
    	// Include the current JWT token
    	config.headers = {'Authorization': "Bearer " + localStorage.getItem('token') || ''}
    	return super.getRequest( config );
  	}
}
```

Then I import those two create other models and extend off of them like so:

```javascript
import BaseModel from './BaseModel'

/**
 * Singular Client Model
 **/

export default class BLAHBLAH extends BaseModel {

  //Empty state
  defaults() {
    return {
<redacted>
    }
  }

  //Mutations
  mutations() {
    return {
      emotion: (emotion) => emotion.toString().toLowerCase()
    }
  }

  //Routes for collecting instance data
  routes() {
    return {
      fetch: '/costings/{client_id}/costings/{id}',
      create: '/costings/{client_id}/costings',
  }
 }
```

**Comment by chrisformula** [comment]
@inventionlabsSydney Awesome thanks so much for the response and the example, much appreciated

**Comment by inventionlabsSydney** [comment]
You're welcome, best of luck! 👍

**Comment by chrisformula** [comment]
Thanks mate

**Comment by rodriigomedeiros** [comment]
It is code stopped working? Is the getRequest method no longer called?

**Comment by rtheunissen** [comment]
@rodriigomedeiros it is now called `createRequest`.

**Comment by CristianaPereira** [comment]
@inventionlabsSydney 
I'm sorry, i never answered back.
At the time my solution was use a [Environment Variable ](https://vuejs-templates.github.io/webpack/env.html) and rewrite the getRequest method on each model.
Your solution look good to me, i'll use it. Thank you!

dev.env.js
`module.exports = merge(prodEnv, {
  NODE_ENV: '"development"',
  VUE_APP_API: '"http://127.0.0.1:8092/"',
  VUE_APP_WHMCS: '"http://127.0.0.1:8080/admin"'
})`

myModel.js

class myModel extends Model {
  getRequest (config) {
    config = config || {}
    config.baseURL = process.env.VUE_APP_API
    config.withCredentials = true
    return super.getRequest(config)
  }
}
