### ISSUE TITLE
Unneeded check if rule returns false

### ISSUE THREAD

**Issue by BehindTheMath** [FiguredLimited/vue-mc#86]
When a rule is checking any additional rules added with `.and()`, it [checks](https://github.com/FiguredLimited/vue-mc/blob/3962dafebc8752aa9d24d3b325bd010c847882ce/src/Validation/index.js#L172) if one of those additional rules returned `false`. However, it appears that the only possible return values for a rule are `true` or a string, so this check is redundant.

**Comment by rtheunissen** [comment]
This allowed for rules to simply return `false`, but in hindsight I think we should enforce a string return.  I have a feeling that there was a good reason for supporting a `false` return but there is no record of that. Notice the failing test that was also removed in efcb2cc
