### ISSUE TITLE
How to use package in NuxtJS?

### ISSUE THREAD

**Issue by mrFANRA** [FiguredLimited/vue-mc#96]
Hello, Rudi! Im trying use package in SSR app on Nuxt. 

Vue starts twice after import Model:
`import {Model} from 'vue-mc';`

![screenshot_4](https://user-images.githubusercontent.com/20259213/52519584-42c8ee80-2c6e-11e9-956b-631af9d5f714.png)

But all is fine in direct import 
`import Model from './downloaded-vue-mc/Structures/Model';`

How to solve this? Thanks!

**Comment by rtheunissen** [comment]
Are you using webpack? I don't know Nuxt at all, sorry. It seems like it's not extracting the vendors properly.

**Comment by ozakha** [comment]
@mrFANRA I am using it inside my nuxtjs app without any problem.
Simply create your own model/collection based on original and just import it where you need it.
But I would not recommend to use it in stores.
